---
openapi: 3.0.0
info:
  title: SVG to PPT
  description: SVG-ből generált képeket Power Point prezentációban megfelelő új diákra beillesztő rendszer
  version: 1.0.0
tags:
- name: conversion-configuration
- name: auth
- name: conversion-status
- name: content-provider
- name: svg-parser
- name: ppt-exporter
paths:
  /login:
    post:
      tags:
      - auth
      summary: Bejelentkezés
      description: Lehetőséget ad a felhasználónak bejelentkezésre
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Felhasználónév
                password:
                  type: string
                  description: Jelszó
                  format: password
      responses:
        "200":
          description: Sikeres bejelentkezés
        "401":
          description: Sikertelen bejelentkezés
  /register:
    post:
      tags:
      - auth
      summary: Regisztráció
      description: Lehetőséget ad a felhasználónak regisztrációra
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Email:
                  type: string
                  description: Email cím
                FirstName:
                  type: string
                  description: Keresztnév
                LastName:
                  type: string
                  description: Vezetéknév
                Password:
                  type: string
                  description: Jelszó
                  format: password
      responses:
        "200":
          description: Sikeres bejelentkezés
  /configs:
    get:
      tags:
      - conversion-configuration
      summary: Jelenlegi konfiguráció lekérése
      responses:
        "200":
          description: Sikeres lekérés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
    put:
      tags:
      - conversion-configuration
      summary: Konfiguráció módosítása
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        "200":
          description: Sikeres módosítás
  /configs/{id}:
    get:
      tags: 
      - conversion-configuration
      summary: Adott konfiguráció lekérdezése
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Sikeres lekérés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /status/{id}:
    parameters:
    - name: id
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    get:
      tags:
      - conversion-status
      summary: Folyamat státuszának lekérdezése
      responses:
        "200":
          description: Sikeres státusz lekérdezés
          content:
            application/json:
              schema:
                type: object
                properties:
                  ConfigId:
                    type: string
                    title: Konfiguráció azonosító
                  Status:
                    type: string
                    title: Státusz
                  ResultFileId:
                    type: string
                    title: Eredmény fájl azonosító
    post:
      tags:
      - conversion-status
      summary: Folyamat státuszának beállítása
      requestBody:
        content:
          application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    title: Státusz
      responses:
        "200":
          description: Sikeres státusz állítás
  /status/{id}/done:
    parameters:
    - name: id
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    post:
      tags:
      - conversion-status
      summary: Folyamat befejezése státusz beállítása
      requestBody:
        content:
          application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    title: Státusz
                  resultFileId:
                    type: string
                    title: Eredmény fájl azonosító
      responses:
        "200":
          description: Sikeres státusz állítás
  /files:
    get:
      tags:
      - conversion-configuration
      summary: Feltöltött fájlok listájának lekérdezése
      responses:
        "200":
          description: Sikeres fájl lista lekérdezés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
    post:
      tags:
      - conversion-configuration
      summary: Új fájl feltöltése
      requestBody:
        content:
          application/vnd.ms-powerpoint:
            schema:
              $ref: '#/components/schemas/BinaryFile'
          application/vnd.openxmlformats-officedocument.presentationml.presentation:
            schema:
              $ref: '#/components/schemas/BinaryFile'
      responses:
        "200":
          description: Sikeres feltöltés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleId'
  /files/{id}:
    get:
      tags:
      - conversion-configuration
      summary: Fájl letöltése
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Fájl letöltése sikeres
          content:
            application/vnd.openxmlformats-officedocument.presentationml.presentation:
              schema:
                $ref: '#/components/schemas/BinaryFile'
  /startSvg/{id}:
    post:
      summary: SVG feldolgozás elindítása
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Konfiguráció azonosítója
      tags:
      - svg-parser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SingleId'
      responses:
        "200":
          description: SVG feldolgozás indítása sikeres
        "422":
          description: Nem található entitás a megadott azonosítóval
  /startPpt/{id}:
    post:
      summary: PPT generálás elindítása
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Konfiguráció azonosítója
      requestBody:
        description: Beinzertálandó képek azonosítója
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
      tags:
      - ppt-exporter
      responses:
        "200":
          description: PPT generálás indítása sikeres
  /start/{id}:
    post:
      tags:
      - conversion-configuration
      summary: Adott azonosítójú konfigurációval feldolgozás indítása
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Feldolgozás indítása sikeres
components:
  schemas:
    SingleId:
      type: object
      properties:
        id:
          type: string
          description: Objektum azonosítója
    BinaryFile:
      type: string
      format: binary
      description: Bináris fájl
    Configuration:
      type: object
      properties:
        afterSlide:
          type: integer
          description: Ez után a dia utánra lesznek beszúrva a képek
        maxImages:
          type: integer
          description: Legfeljebb ennyi kép szúrható be
        animation:
          type: string
          enum:
          - simple
          description: Animáció
        pptFileId:
          type: string
          description: Prezentációs fájl azonosítója
        svgFileId:
          type: string
          nullable: false
          description: SVG fájl azonosítója
