services:
    configuration:    
        container_name: ${CONFIG_NAME}
        hostname: ${CONFIG_NAME}
        build: .
        ports:
            - "27001:443"
        networks:
            - database_svg2ppt
        volumes:
            - ${ASPNETCORE_SSL_PATH}:/https:ro
        env_file: 
            - ../../../.env
        environment:
            DatabaseSettings:DatabaseName: ${MONGO_DATABASE}
            DatabaseSettings:FilesCollectionName: ${COLLECTION_FILES}
            DatabaseSettings:ConfigsCollectionName: ${COLLECTION_CONFIGS}
            DatabaseSettings:ConnectionString: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_NAME}:27017/?authSource=${MONGO_DATABASE}
            PropertySettings:StatusEndpoint: http://${STATUS_NAME}/status/{0}
            PropertySettings:StatusProp: ${PROPERTY_STATUS}
            PropertySettings:SvgEndpoint: http://${SVG_NAME}/startSvg/{0}            
networks:
  database_svg2ppt:
    external: true