services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./mongod.conf:/etc/mongod.conf
            - ./initdb.d/:/docker-entrypoint-initdb.d/
            - ./data/db/:/data/db/
            - ./data/log/:/var/log/mongodb/
        env_file: 
            - ./.env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - "27018:27017"
        command: ["-f", "/etc/mongod.conf"]