services:
    configuration:    
        container_name: ${PPT_NAME}
        hostname: ${PPT_NAME}
        build: .
        ports:
            - "27002:80"
        networks:
            - database_svg2ppt
        env_file: 
            - ../../../.env
        environment: 
            DatabaseSettings:DatabaseName: ${MONGO_DATABASE}
            DatabaseSettings:FilesCollectionName: ${COLLECTION_FILES}
            DatabaseSettings:ConfigsCollectionName: ${COLLECTION_CONFIGS}
            DatabaseSettings:ConnectionString: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_NAME}:27017/?authSource=${MONGO_DATABASE}
            PropertySettings:EndIdName: FileId
            PropertySettings:EndFileName: Name
            PropertySettings:AfterSlideProp: AfterSlide
            PropertySettings:AnimationProp: Animation
            PropertySettings:PptFileIdProp: PptFileId
            PropertySettings:StatusEndpoint: http://${STATUS_NAME}/status/{0}
            PropertySettings:StatusProp: ${PROPERTY_STATUS}
            PropertySettings:StatusBeginMessage: Processing PPT
            PropertySettings:StatusEndMessage: Done
networks:
  database_svg2ppt:
    external: true