services:
    configuration:    
        container_name: ${STATUS_NAME}
        hostname: ${STATUS_NAME}
        build: .
        ports:
            - "27004:443"
        networks:
            - database_svg2ppt
        volumes:
            - ${ASPNETCORE_SSL_PATH}:/https:ro
        env_file: 
            - ../../../.env
        environment: 
            DatabaseSettings:DatabaseName: ${MONGO_DATABASE}
            DatabaseSettings:StatusCollectionName: ${COLLECTION_STATUS}
            DatabaseSettings:ConnectionString: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_NAME}:27017/?authSource=${MONGO_DATABASE}
networks:
  database_svg2ppt:
    external: true